server:
  port: 7700
  servlet:
    context-path: /ssqmq

logging:
  config: classpath:logback.xml

ssqmq:
  server:
    port: 6800
    host: 127.0.0.1
    username: username
    password: password
    link-delay: 2000

